<?
echo '<center>';
if($pcc3 == 'true'){require "pc.c";}else{echo "<font color=\"blue\">O arquivo pc.c não existe</font><br>";}
if($maph3 == 'true'){require "map.h";}else{echo "<font color=\"blue\">O arquivo map.h não existe</font><br>";}
if($atcommandc3 == 'true'){require "atcommand.c";}else{echo "<font color=\"blue\">O arquivo atcommand.c não existe</font><br>";}
if($battlec3 == 'true'){require "battle.c";}else{echo "<font color=\"blue\">O arquivo battle.c não existe</font><br>";}
if($battleh3 == 'true'){require "battle.h";}else{echo "<font color=\"blue\">O arquivo battle.h não existe</font><br>";}
if($mobc3 == 'true'){require "mob.c";}else{echo "<font color=\"blue\">O arquivo mob.c não existe</font><br>";}
if($scriptc3 == 'true'){require "script.c";}else{echo "<font color=\"blue\">O arquivo mob.c não existe</font><br>";}
require "atscrchar.c";
echo '</center>';
?>